// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: voice_agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PCM16, 16kHz mono. Each chunk is 20–40ms (320–640 bytes).
// Go sends chunks into a bounded channel (cap=8) before forwarding here
// to apply natural backpressure and prevent flooding Python.
type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	EndOfStream   bool                   `protobuf:"varint,2,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_voice_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_voice_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_voice_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Partial or final transcript from Whisper.
// is_final=true only after transcript is stable for 300ms (stability window).
type TranscriptChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptChunk) Reset() {
	*x = TranscriptChunk{}
	mi := &file_voice_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptChunk) ProtoMessage() {}

func (x *TranscriptChunk) ProtoReflect() protoreflect.Message {
	mi := &file_voice_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptChunk.ProtoReflect.Descriptor instead.
func (*TranscriptChunk) Descriptor() ([]byte, []int) {
	return file_voice_agent_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *TranscriptChunk) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscriptChunk) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// One turn of conversation history sent to CSM for voice conditioning.
// role "0" = assistant, "1" = user — matches CSM speaker ID convention.
// audio is PCM16 at 24kHz (CSM sample rate); omit for turns without recorded audio.
type ConversationTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Audio         []byte                 `protobuf:"bytes,3,opt,name=audio,proto3" json:"audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationTurn) Reset() {
	*x = ConversationTurn{}
	mi := &file_voice_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurn) ProtoMessage() {}

func (x *ConversationTurn) ProtoReflect() protoreflect.Message {
	mi := &file_voice_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurn.ProtoReflect.Descriptor instead.
func (*ConversationTurn) Descriptor() ([]byte, []int) {
	return file_voice_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationTurn) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationTurn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ConversationTurn) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

// Text token(s) destined for TTS synthesis.
// context carries the last CONTEXT_TURNS (3) audio turns for CSM conditioning.
type TextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	EndOfStream   bool                   `protobuf:"varint,2,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Context       []*ConversationTurn    `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_voice_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_voice_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_voice_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TextChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

func (x *TextChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TextChunk) GetContext() []*ConversationTurn {
	if x != nil {
		return x.Context
	}
	return nil
}

// Pre-cached filler audio request (no inference — served from memory).
type FillerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of: "Mm-hmm.", "Hmm...", "Let me think about that.",
	//
	//	"Sure!", "One moment.", "Right.", "Got it."
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillerRequest) Reset() {
	*x = FillerRequest{}
	mi := &file_voice_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillerRequest) ProtoMessage() {}

func (x *FillerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_voice_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillerRequest.ProtoReflect.Descriptor instead.
func (*FillerRequest) Descriptor() ([]byte, []int) {
	return file_voice_agent_proto_rawDescGZIP(), []int{4}
}

func (x *FillerRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_voice_agent_proto protoreflect.FileDescriptor

const file_voice_agent_proto_rawDesc = "" +
	"\n" +
	"\x11voice_agent.proto\x12\vvoice_agent\"c\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\"\n" +
	"\rend_of_stream\x18\x02 \x01(\bR\vendOfStream\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x83\x01\n" +
	"\x0fTranscriptChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\"P\n" +
	"\x10ConversationTurn\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05audio\x18\x03 \x01(\fR\x05audio\"\x9b\x01\n" +
	"\tTextChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\"\n" +
	"\rend_of_stream\x18\x02 \x01(\bR\vendOfStream\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x127\n" +
	"\acontext\x18\x04 \x03(\v2\x1d.voice_agent.ConversationTurnR\acontext\"!\n" +
	"\rFillerRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key2[\n" +
	"\n" +
	"STTService\x12M\n" +
	"\x10StreamTranscribe\x12\x17.voice_agent.AudioChunk\x1a\x1c.voice_agent.TranscriptChunk(\x010\x012\x97\x01\n" +
	"\n" +
	"TTSService\x12G\n" +
	"\x10StreamSynthesize\x12\x16.voice_agent.TextChunk\x1a\x17.voice_agent.AudioChunk(\x010\x01\x12@\n" +
	"\tGetFiller\x12\x1a.voice_agent.FillerRequest\x1a\x17.voice_agent.AudioChunkB\x1dZ\x1bvoice-agent/go-server/protob\x06proto3"

var (
	file_voice_agent_proto_rawDescOnce sync.Once
	file_voice_agent_proto_rawDescData []byte
)

func file_voice_agent_proto_rawDescGZIP() []byte {
	file_voice_agent_proto_rawDescOnce.Do(func() {
		file_voice_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_agent_proto_rawDesc), len(file_voice_agent_proto_rawDesc)))
	})
	return file_voice_agent_proto_rawDescData
}

var file_voice_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_voice_agent_proto_goTypes = []any{
	(*AudioChunk)(nil),       // 0: voice_agent.AudioChunk
	(*TranscriptChunk)(nil),  // 1: voice_agent.TranscriptChunk
	(*ConversationTurn)(nil), // 2: voice_agent.ConversationTurn
	(*TextChunk)(nil),        // 3: voice_agent.TextChunk
	(*FillerRequest)(nil),    // 4: voice_agent.FillerRequest
}
var file_voice_agent_proto_depIdxs = []int32{
	2, // 0: voice_agent.TextChunk.context:type_name -> voice_agent.ConversationTurn
	0, // 1: voice_agent.STTService.StreamTranscribe:input_type -> voice_agent.AudioChunk
	3, // 2: voice_agent.TTSService.StreamSynthesize:input_type -> voice_agent.TextChunk
	4, // 3: voice_agent.TTSService.GetFiller:input_type -> voice_agent.FillerRequest
	1, // 4: voice_agent.STTService.StreamTranscribe:output_type -> voice_agent.TranscriptChunk
	0, // 5: voice_agent.TTSService.StreamSynthesize:output_type -> voice_agent.AudioChunk
	0, // 6: voice_agent.TTSService.GetFiller:output_type -> voice_agent.AudioChunk
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_voice_agent_proto_init() }
func file_voice_agent_proto_init() {
	if File_voice_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_agent_proto_rawDesc), len(file_voice_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_voice_agent_proto_goTypes,
		DependencyIndexes: file_voice_agent_proto_depIdxs,
		MessageInfos:      file_voice_agent_proto_msgTypes,
	}.Build()
	File_voice_agent_proto = out.File
	file_voice_agent_proto_goTypes = nil
	file_voice_agent_proto_depIdxs = nil
}
