// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: voice_agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	STTService_StreamTranscribe_FullMethodName = "/voice_agent.STTService/StreamTranscribe"
)

// STTServiceClient is the client API for STTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client streams 20–40ms PCM16 audio chunks.
// Server streams partial transcripts (is_final=false) and one final committed
// transcript (is_final=true) per utterance.
type STTServiceClient interface {
	StreamTranscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptChunk], error)
}

type sTTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSTTServiceClient(cc grpc.ClientConnInterface) STTServiceClient {
	return &sTTServiceClient{cc}
}

func (c *sTTServiceClient) StreamTranscribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AudioChunk, TranscriptChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &STTService_ServiceDesc.Streams[0], STTService_StreamTranscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunk, TranscriptChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type STTService_StreamTranscribeClient = grpc.BidiStreamingClient[AudioChunk, TranscriptChunk]

// STTServiceServer is the server API for STTService service.
// All implementations must embed UnimplementedSTTServiceServer
// for forward compatibility.
//
// Client streams 20–40ms PCM16 audio chunks.
// Server streams partial transcripts (is_final=false) and one final committed
// transcript (is_final=true) per utterance.
type STTServiceServer interface {
	StreamTranscribe(grpc.BidiStreamingServer[AudioChunk, TranscriptChunk]) error
	mustEmbedUnimplementedSTTServiceServer()
}

// UnimplementedSTTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSTTServiceServer struct{}

func (UnimplementedSTTServiceServer) StreamTranscribe(grpc.BidiStreamingServer[AudioChunk, TranscriptChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamTranscribe not implemented")
}
func (UnimplementedSTTServiceServer) mustEmbedUnimplementedSTTServiceServer() {}
func (UnimplementedSTTServiceServer) testEmbeddedByValue()                    {}

// UnsafeSTTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to STTServiceServer will
// result in compilation errors.
type UnsafeSTTServiceServer interface {
	mustEmbedUnimplementedSTTServiceServer()
}

func RegisterSTTServiceServer(s grpc.ServiceRegistrar, srv STTServiceServer) {
	// If the following call panics, it indicates UnimplementedSTTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&STTService_ServiceDesc, srv)
}

func _STTService_StreamTranscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(STTServiceServer).StreamTranscribe(&grpc.GenericServerStream[AudioChunk, TranscriptChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type STTService_StreamTranscribeServer = grpc.BidiStreamingServer[AudioChunk, TranscriptChunk]

// STTService_ServiceDesc is the grpc.ServiceDesc for STTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var STTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice_agent.STTService",
	HandlerType: (*STTServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTranscribe",
			Handler:       _STTService_StreamTranscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "voice_agent.proto",
}

const (
	TTSService_StreamSynthesize_FullMethodName = "/voice_agent.TTSService/StreamSynthesize"
	TTSService_GetFiller_FullMethodName        = "/voice_agent.TTSService/GetFiller"
)

// TTSServiceClient is the client API for TTSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Client streams text tokens with conversation context.
// Server streams PCM16 audio chunks (24kHz) as synthesis progresses.
// Max 2 concurrent StreamSynthesize calls (semaphore in Python) — this is
// intentional backpressure: the 3rd caller blocks until a slot is free,
// which propagates back to the Go LLM consumer.
//
// GetFiller is unary and always returns immediately (cached bytes, no GPU).
type TTSServiceClient interface {
	StreamSynthesize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TextChunk, AudioChunk], error)
	GetFiller(ctx context.Context, in *FillerRequest, opts ...grpc.CallOption) (*AudioChunk, error)
}

type tTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSServiceClient(cc grpc.ClientConnInterface) TTSServiceClient {
	return &tTSServiceClient{cc}
}

func (c *tTSServiceClient) StreamSynthesize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TextChunk, AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[0], TTSService_StreamSynthesize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TextChunk, AudioChunk]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_StreamSynthesizeClient = grpc.BidiStreamingClient[TextChunk, AudioChunk]

func (c *tTSServiceClient) GetFiller(ctx context.Context, in *FillerRequest, opts ...grpc.CallOption) (*AudioChunk, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AudioChunk)
	err := c.cc.Invoke(ctx, TTSService_GetFiller_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TTSServiceServer is the server API for TTSService service.
// All implementations must embed UnimplementedTTSServiceServer
// for forward compatibility.
//
// Client streams text tokens with conversation context.
// Server streams PCM16 audio chunks (24kHz) as synthesis progresses.
// Max 2 concurrent StreamSynthesize calls (semaphore in Python) — this is
// intentional backpressure: the 3rd caller blocks until a slot is free,
// which propagates back to the Go LLM consumer.
//
// GetFiller is unary and always returns immediately (cached bytes, no GPU).
type TTSServiceServer interface {
	StreamSynthesize(grpc.BidiStreamingServer[TextChunk, AudioChunk]) error
	GetFiller(context.Context, *FillerRequest) (*AudioChunk, error)
	mustEmbedUnimplementedTTSServiceServer()
}

// UnimplementedTTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServiceServer struct{}

func (UnimplementedTTSServiceServer) StreamSynthesize(grpc.BidiStreamingServer[TextChunk, AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamSynthesize not implemented")
}
func (UnimplementedTTSServiceServer) GetFiller(context.Context, *FillerRequest) (*AudioChunk, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFiller not implemented")
}
func (UnimplementedTTSServiceServer) mustEmbedUnimplementedTTSServiceServer() {}
func (UnimplementedTTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServiceServer will
// result in compilation errors.
type UnsafeTTSServiceServer interface {
	mustEmbedUnimplementedTTSServiceServer()
}

func RegisterTTSServiceServer(s grpc.ServiceRegistrar, srv TTSServiceServer) {
	// If the following call panics, it indicates UnimplementedTTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSService_ServiceDesc, srv)
}

func _TTSService_StreamSynthesize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TTSServiceServer).StreamSynthesize(&grpc.GenericServerStream[TextChunk, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_StreamSynthesizeServer = grpc.BidiStreamingServer[TextChunk, AudioChunk]

func _TTSService_GetFiller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FillerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TTSServiceServer).GetFiller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TTSService_GetFiller_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TTSServiceServer).GetFiller(ctx, req.(*FillerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TTSService_ServiceDesc is the grpc.ServiceDesc for TTSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice_agent.TTSService",
	HandlerType: (*TTSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFiller",
			Handler:    _TTSService_GetFiller_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSynthesize",
			Handler:       _TTSService_StreamSynthesize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "voice_agent.proto",
}
