# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voice_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11voice_agent.proto\x12\x0bvoice_agent\"E\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x15\n\rend_of_stream\x18\x02 \x01(\x08\x12\x12\n\nsession_id\x18\x03 \x01(\t\"[\n\x0fTranscriptChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08is_final\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\"=\n\x10\x43onversationTurn\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05\x61udio\x18\x03 \x01(\x0c\"t\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x15\n\rend_of_stream\x18\x02 \x01(\x08\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12.\n\x07\x63ontext\x18\x04 \x03(\x0b\x32\x1d.voice_agent.ConversationTurn\"\x1c\n\rFillerRequest\x12\x0b\n\x03key\x18\x01 \x01(\t2[\n\nSTTService\x12M\n\x10StreamTranscribe\x12\x17.voice_agent.AudioChunk\x1a\x1c.voice_agent.TranscriptChunk(\x01\x30\x01\x32\x97\x01\n\nTTSService\x12G\n\x10StreamSynthesize\x12\x16.voice_agent.TextChunk\x1a\x17.voice_agent.AudioChunk(\x01\x30\x01\x12@\n\tGetFiller\x12\x1a.voice_agent.FillerRequest\x1a\x17.voice_agent.AudioChunkB\x1dZ\x1bvoice-agent/go-server/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033voice-agent/go-server/proto'
  _globals['_AUDIOCHUNK']._serialized_start=34
  _globals['_AUDIOCHUNK']._serialized_end=103
  _globals['_TRANSCRIPTCHUNK']._serialized_start=105
  _globals['_TRANSCRIPTCHUNK']._serialized_end=196
  _globals['_CONVERSATIONTURN']._serialized_start=198
  _globals['_CONVERSATIONTURN']._serialized_end=259
  _globals['_TEXTCHUNK']._serialized_start=261
  _globals['_TEXTCHUNK']._serialized_end=377
  _globals['_FILLERREQUEST']._serialized_start=379
  _globals['_FILLERREQUEST']._serialized_end=407
  _globals['_STTSERVICE']._serialized_start=409
  _globals['_STTSERVICE']._serialized_end=500
  _globals['_TTSSERVICE']._serialized_start=503
  _globals['_TTSSERVICE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
