# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_agent_pb2 as voice__agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voice_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class STTServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    STT Service
    ─────────────────────────────────────────────────────────────────────────────

    Client streams 20–40ms PCM16 audio chunks.
    Server streams partial transcripts (is_final=false) and one final committed
    transcript (is_final=true) per utterance.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTranscribe = channel.stream_stream(
                '/voice_agent.STTService/StreamTranscribe',
                request_serializer=voice__agent__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__agent__pb2.TranscriptChunk.FromString,
                _registered_method=True)


class STTServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    STT Service
    ─────────────────────────────────────────────────────────────────────────────

    Client streams 20–40ms PCM16 audio chunks.
    Server streams partial transcripts (is_final=false) and one final committed
    transcript (is_final=true) per utterance.
    """

    def StreamTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=voice__agent__pb2.AudioChunk.FromString,
                    response_serializer=voice__agent__pb2.TranscriptChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_agent.STTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_agent.STTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class STTService(object):
    """─────────────────────────────────────────────────────────────────────────────
    STT Service
    ─────────────────────────────────────────────────────────────────────────────

    Client streams 20–40ms PCM16 audio chunks.
    Server streams partial transcripts (is_final=false) and one final committed
    transcript (is_final=true) per utterance.
    """

    @staticmethod
    def StreamTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice_agent.STTService/StreamTranscribe',
            voice__agent__pb2.AudioChunk.SerializeToString,
            voice__agent__pb2.TranscriptChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TTSServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    TTS Service
    ─────────────────────────────────────────────────────────────────────────────

    Client streams text tokens with conversation context.
    Server streams PCM16 audio chunks (24kHz) as synthesis progresses.
    Max 2 concurrent StreamSynthesize calls (semaphore in Python) — this is
    intentional backpressure: the 3rd caller blocks until a slot is free,
    which propagates back to the Go LLM consumer.

    GetFiller is unary and always returns immediately (cached bytes, no GPU).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSynthesize = channel.stream_stream(
                '/voice_agent.TTSService/StreamSynthesize',
                request_serializer=voice__agent__pb2.TextChunk.SerializeToString,
                response_deserializer=voice__agent__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.GetFiller = channel.unary_unary(
                '/voice_agent.TTSService/GetFiller',
                request_serializer=voice__agent__pb2.FillerRequest.SerializeToString,
                response_deserializer=voice__agent__pb2.AudioChunk.FromString,
                _registered_method=True)


class TTSServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    TTS Service
    ─────────────────────────────────────────────────────────────────────────────

    Client streams text tokens with conversation context.
    Server streams PCM16 audio chunks (24kHz) as synthesis progresses.
    Max 2 concurrent StreamSynthesize calls (semaphore in Python) — this is
    intentional backpressure: the 3rd caller blocks until a slot is free,
    which propagates back to the Go LLM consumer.

    GetFiller is unary and always returns immediately (cached bytes, no GPU).
    """

    def StreamSynthesize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFiller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSynthesize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSynthesize,
                    request_deserializer=voice__agent__pb2.TextChunk.FromString,
                    response_serializer=voice__agent__pb2.AudioChunk.SerializeToString,
            ),
            'GetFiller': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFiller,
                    request_deserializer=voice__agent__pb2.FillerRequest.FromString,
                    response_serializer=voice__agent__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice_agent.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice_agent.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService(object):
    """─────────────────────────────────────────────────────────────────────────────
    TTS Service
    ─────────────────────────────────────────────────────────────────────────────

    Client streams text tokens with conversation context.
    Server streams PCM16 audio chunks (24kHz) as synthesis progresses.
    Max 2 concurrent StreamSynthesize calls (semaphore in Python) — this is
    intentional backpressure: the 3rd caller blocks until a slot is free,
    which propagates back to the Go LLM consumer.

    GetFiller is unary and always returns immediately (cached bytes, no GPU).
    """

    @staticmethod
    def StreamSynthesize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice_agent.TTSService/StreamSynthesize',
            voice__agent__pb2.TextChunk.SerializeToString,
            voice__agent__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFiller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voice_agent.TTSService/GetFiller',
            voice__agent__pb2.FillerRequest.SerializeToString,
            voice__agent__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
